[api]
host = "127.0.0.1"
port = 8000
debug = true
prefix = "/api/v1"
project_name = "BYOCRUDA"
description = "Build Your Own CRUD Application"
version = "0.1.0"

[database]
url = "sqlite:///./byocruda.db"
echo = false

[security]
database_enable = false
ldap_enable = false
api_enable = true
https_enable = false

[security.database]
secret_key_env_variable = "BYOCRUDA_SECRET_KEY" 
crypt_algorithm = "aes-256-cfb"

[security.ldap]
ldap_uri = ""
ldap_bind_user = ""
ldap_base = ""
ldap_filter = ""

[security.api]
signing_algorithm = "HS256"
access_token_expire_minutes = 30

[logging]
level = "DEBUG"
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
file_path = "logs/byocruda.log"
rotation = "500 MB"
retention = "10 days"
